plugins {
    id 'com.android.application'
}

android {
    namespace 'rs.brainno.stakuvamo'
    compileSdk 36

    defaultConfig {
        applicationId 'rs.brainno.stakuvamo'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        buildConfig = false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
